[[bond]]
source = "tpknam1qqmhsxy3wmq09rs7t895rg680vu9c2vraerclgxnawp27ed3qyawv7vuya4"
validator = "tnam1q8azt2cpqmc6tr2gvg5v62e4jr0t9327yupaf595"
amount = "135"

[bond.signatures]
tpknam1qqmhsxy3wmq09rs7t895rg680vu9c2vraerclgxnawp27ed3qyawv7vuya4 = "signam1qru6sxk0hwwyxndc9yclczpztnh3q9nr4rwmer0hg5y0xmk83qt6zsj3gk8urlf80pnyt04r5j83dpck2q9akxnkjdhlx4wg2dshgjqrzej4mm"
